version: '3.8'

services:
  zk-api:
    image: julienberanger/zk-api:latest
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    environment:
      - NODE_ENV=${NODE_ENV}
      - KMS_URL=${KMS_URL}
      - ADMIN_MLKEM_PUBLIC_KEY=${ADMIN_MLKEM_PUBLIC_KEY}
      - ADMIN_MLKEM_PRIVATE_KEY=${ADMIN_MLKEM_PRIVATE_KEY}
    restart: unless-stopped
